//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountinformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountinformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="accountnumber" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}accountnumber"/>
 *         &lt;element name="accountstatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}accountstatus"/>
 *         &lt;element name="passcode" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}passcode"/>
 *         &lt;element name="market" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}market"/>
 *         &lt;element name="submarket" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}submarket"/>
 *         &lt;element name="accounttype" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}accounttype"/>
 *         &lt;element name="activationdate" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}activationdate" minOccurs="0"/>
 *         &lt;element name="airtimeexpiration" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}airtimeexpiration" minOccurs="0"/>
 *         &lt;element name="servicecanceldate" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}servicecanceldate" minOccurs="0"/>
 *         &lt;element name="subscriptionstatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}subscriptionstatus" minOccurs="0"/>
 *         &lt;element name="ivrlanguage" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}ivrlanguage" minOccurs="0"/>
 *         &lt;element name="ivrussdstatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}ivrussdstatus" minOccurs="0"/>
 *         &lt;element name="cgsa" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}cgsa" minOccurs="0"/>
 *         &lt;element name="moneybalanceinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}moneybalanceinfo" minOccurs="0"/>
 *         &lt;element name="passcodestatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}passcodestatus" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountinformation", propOrder = {

})
public class Accountinformation {

    @XmlElement(required = true)
    protected String accountnumber;
    @XmlElement(required = true)
    protected Accountstatus accountstatus;
    @XmlElement(required = true)
    protected String passcode;
    @XmlElement(required = true)
    protected String market;
    @XmlElement(required = true)
    protected String submarket;
    @XmlElement(required = true)
    protected BigInteger accounttype;
    protected String activationdate;
    protected String airtimeexpiration;
    protected String servicecanceldate;
    protected Subscriptionstatus subscriptionstatus;
    protected BigInteger ivrlanguage;
    protected Ivrussdstatus ivrussdstatus;
    protected String cgsa;
    protected Moneybalanceinfo moneybalanceinfo;
    protected BigInteger passcodestatus;

    /**
     * Gets the value of the accountnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * Sets the value of the accountnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountnumber(String value) {
        this.accountnumber = value;
    }

    /**
     * Gets the value of the accountstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Accountstatus }
     *     
     */
    public Accountstatus getAccountstatus() {
        return accountstatus;
    }

    /**
     * Sets the value of the accountstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accountstatus }
     *     
     */
    public void setAccountstatus(Accountstatus value) {
        this.accountstatus = value;
    }

    /**
     * Gets the value of the passcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasscode() {
        return passcode;
    }

    /**
     * Sets the value of the passcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasscode(String value) {
        this.passcode = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarket(String value) {
        this.market = value;
    }

    /**
     * Gets the value of the submarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmarket() {
        return submarket;
    }

    /**
     * Sets the value of the submarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmarket(String value) {
        this.submarket = value;
    }

    /**
     * Gets the value of the accounttype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccounttype() {
        return accounttype;
    }

    /**
     * Sets the value of the accounttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccounttype(BigInteger value) {
        this.accounttype = value;
    }

    /**
     * Gets the value of the activationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationdate() {
        return activationdate;
    }

    /**
     * Sets the value of the activationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationdate(String value) {
        this.activationdate = value;
    }

    /**
     * Gets the value of the airtimeexpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirtimeexpiration() {
        return airtimeexpiration;
    }

    /**
     * Sets the value of the airtimeexpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirtimeexpiration(String value) {
        this.airtimeexpiration = value;
    }

    /**
     * Gets the value of the servicecanceldate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicecanceldate() {
        return servicecanceldate;
    }

    /**
     * Sets the value of the servicecanceldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicecanceldate(String value) {
        this.servicecanceldate = value;
    }

    /**
     * Gets the value of the subscriptionstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Subscriptionstatus }
     *     
     */
    public Subscriptionstatus getSubscriptionstatus() {
        return subscriptionstatus;
    }

    /**
     * Sets the value of the subscriptionstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subscriptionstatus }
     *     
     */
    public void setSubscriptionstatus(Subscriptionstatus value) {
        this.subscriptionstatus = value;
    }

    /**
     * Gets the value of the ivrlanguage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIvrlanguage() {
        return ivrlanguage;
    }

    /**
     * Sets the value of the ivrlanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIvrlanguage(BigInteger value) {
        this.ivrlanguage = value;
    }

    /**
     * Gets the value of the ivrussdstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Ivrussdstatus }
     *     
     */
    public Ivrussdstatus getIvrussdstatus() {
        return ivrussdstatus;
    }

    /**
     * Sets the value of the ivrussdstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ivrussdstatus }
     *     
     */
    public void setIvrussdstatus(Ivrussdstatus value) {
        this.ivrussdstatus = value;
    }

    /**
     * Gets the value of the cgsa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCgsa() {
        return cgsa;
    }

    /**
     * Sets the value of the cgsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCgsa(String value) {
        this.cgsa = value;
    }

    /**
     * Gets the value of the moneybalanceinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Moneybalanceinfo }
     *     
     */
    public Moneybalanceinfo getMoneybalanceinfo() {
        return moneybalanceinfo;
    }

    /**
     * Sets the value of the moneybalanceinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moneybalanceinfo }
     *     
     */
    public void setMoneybalanceinfo(Moneybalanceinfo value) {
        this.moneybalanceinfo = value;
    }

    /**
     * Gets the value of the passcodestatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPasscodestatus() {
        return passcodestatus;
    }

    /**
     * Sets the value of the passcodestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPasscodestatus(BigInteger value) {
        this.passcodestatus = value;
    }

}
