//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for featureinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="featureinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="featurecode" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featurecode"/>
 *         &lt;element name="featurestatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featurestatus"/>
 *         &lt;element name="featurechargeinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featurechargeinfo" minOccurs="0"/>
 *         &lt;element name="featurebalanceinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featurebalanceinfo" minOccurs="0"/>
 *         &lt;element name="servicebalanceinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}servicebalanceinfo" minOccurs="0"/>
 *         &lt;element name="expirationdate" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}expirationdate" minOccurs="0"/>
 *         &lt;element name="graceperiodexpirationdate" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}expirationdate" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "featureinfo", propOrder = {

})
public class Featureinfo {

    @XmlElement(required = true)
    protected String featurecode;
    @XmlElement(required = true)
    protected Featurestatus featurestatus;
    protected Featurechargeinfo featurechargeinfo;
    protected Featurebalanceinfo featurebalanceinfo;
    protected Servicebalanceinfo servicebalanceinfo;
    protected String expirationdate;
    protected String graceperiodexpirationdate;

    /**
     * Gets the value of the featurecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeaturecode() {
        return featurecode;
    }

    /**
     * Sets the value of the featurecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeaturecode(String value) {
        this.featurecode = value;
    }

    /**
     * Gets the value of the featurestatus property.
     * 
     * @return
     *     possible object is
     *     {@link Featurestatus }
     *     
     */
    public Featurestatus getFeaturestatus() {
        return featurestatus;
    }

    /**
     * Sets the value of the featurestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Featurestatus }
     *     
     */
    public void setFeaturestatus(Featurestatus value) {
        this.featurestatus = value;
    }

    /**
     * Gets the value of the featurechargeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Featurechargeinfo }
     *     
     */
    public Featurechargeinfo getFeaturechargeinfo() {
        return featurechargeinfo;
    }

    /**
     * Sets the value of the featurechargeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Featurechargeinfo }
     *     
     */
    public void setFeaturechargeinfo(Featurechargeinfo value) {
        this.featurechargeinfo = value;
    }

    /**
     * Gets the value of the featurebalanceinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Featurebalanceinfo }
     *     
     */
    public Featurebalanceinfo getFeaturebalanceinfo() {
        return featurebalanceinfo;
    }

    /**
     * Sets the value of the featurebalanceinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Featurebalanceinfo }
     *     
     */
    public void setFeaturebalanceinfo(Featurebalanceinfo value) {
        this.featurebalanceinfo = value;
    }

    /**
     * Gets the value of the servicebalanceinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Servicebalanceinfo }
     *     
     */
    public Servicebalanceinfo getServicebalanceinfo() {
        return servicebalanceinfo;
    }

    /**
     * Sets the value of the servicebalanceinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Servicebalanceinfo }
     *     
     */
    public void setServicebalanceinfo(Servicebalanceinfo value) {
        this.servicebalanceinfo = value;
    }

    /**
     * Gets the value of the expirationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationdate() {
        return expirationdate;
    }

    /**
     * Sets the value of the expirationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationdate(String value) {
        this.expirationdate = value;
    }

    /**
     * Gets the value of the graceperiodexpirationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraceperiodexpirationdate() {
        return graceperiodexpirationdate;
    }

    /**
     * Sets the value of the graceperiodexpirationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraceperiodexpirationdate(String value) {
        this.graceperiodexpirationdate = value;
    }

}
