//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multilineinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multilineinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="primaryinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}primaryinfo"/>
 *         &lt;element name="members" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}members" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multilineinfo", propOrder = {

})
public class Multilineinfo {

    @XmlElement(required = true)
    protected Primaryinfo primaryinfo;
    protected Members members;

    /**
     * Gets the value of the primaryinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Primaryinfo }
     *     
     */
    public Primaryinfo getPrimaryinfo() {
        return primaryinfo;
    }

    /**
     * Sets the value of the primaryinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Primaryinfo }
     *     
     */
    public void setPrimaryinfo(Primaryinfo value) {
        this.primaryinfo = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link Members }
     *     
     */
    public Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link Members }
     *     
     */
    public void setMembers(Members value) {
        this.members = value;
    }

}
