//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="paymentamount" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}quantity"/>
 *         &lt;element name="paymentdatetime" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}datetime"/>
 *         &lt;element name="paymenttimezone" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}timezone"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payment", propOrder = {

})
public class Payment {

    @XmlElement(required = true)
    protected String paymentamount;
    @XmlElement(required = true)
    protected String paymentdatetime;
    @XmlElement(required = true)
    protected String paymenttimezone;

    /**
     * Gets the value of the paymentamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentamount() {
        return paymentamount;
    }

    /**
     * Sets the value of the paymentamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentamount(String value) {
        this.paymentamount = value;
    }

    /**
     * Gets the value of the paymentdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentdatetime() {
        return paymentdatetime;
    }

    /**
     * Sets the value of the paymentdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentdatetime(String value) {
        this.paymentdatetime = value;
    }

    /**
     * Gets the value of the paymenttimezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymenttimezone() {
        return paymenttimezone;
    }

    /**
     * Sets the value of the paymenttimezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymenttimezone(String value) {
        this.paymenttimezone = value;
    }

}
