//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for promotioncredit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="promotioncredit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="promotioncreditamount" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}quantity"/>
 *         &lt;element name="promotioncreditdatetime" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}datetime"/>
 *         &lt;element name="promotioncredittimezone" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}timezone"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "promotioncredit", propOrder = {

})
public class Promotioncredit {

    @XmlElement(required = true)
    protected String promotioncreditamount;
    @XmlElement(required = true)
    protected String promotioncreditdatetime;
    @XmlElement(required = true)
    protected String promotioncredittimezone;

    /**
     * Gets the value of the promotioncreditamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotioncreditamount() {
        return promotioncreditamount;
    }

    /**
     * Sets the value of the promotioncreditamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotioncreditamount(String value) {
        this.promotioncreditamount = value;
    }

    /**
     * Gets the value of the promotioncreditdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotioncreditdatetime() {
        return promotioncreditdatetime;
    }

    /**
     * Sets the value of the promotioncreditdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotioncreditdatetime(String value) {
        this.promotioncreditdatetime = value;
    }

    /**
     * Gets the value of the promotioncredittimezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotioncredittimezone() {
        return promotioncredittimezone;
    }

    /**
     * Sets the value of the promotioncredittimezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotioncredittimezone(String value) {
        this.promotioncredittimezone = value;
    }

}
