//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rateplaninfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rateplaninfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rateplancode" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplancode"/>
 *         &lt;element name="rateplanstatus" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplanstatus"/>
 *         &lt;element name="rateplanexpirationdate" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}expirationdate" minOccurs="0"/>
 *         &lt;element name="rateplanserviceinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplanserviceinfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rateplanfamily" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplanfamily"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rateplaninfo", propOrder = {
    "rateplancode",
    "rateplanstatus",
    "rateplanexpirationdate",
    "rateplanserviceinfo",
    "rateplanfamily"
})
public class Rateplaninfo {

    @XmlElement(required = true)
    protected String rateplancode;
    @XmlElement(required = true)
    protected Rateplanstatus rateplanstatus;
    protected String rateplanexpirationdate;
    protected List<Rateplanserviceinfo> rateplanserviceinfo;
    @XmlElement(required = true)
    protected BigInteger rateplanfamily;

    /**
     * Gets the value of the rateplancode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateplancode() {
        return rateplancode;
    }

    /**
     * Sets the value of the rateplancode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateplancode(String value) {
        this.rateplancode = value;
    }

    /**
     * Gets the value of the rateplanstatus property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplanstatus }
     *     
     */
    public Rateplanstatus getRateplanstatus() {
        return rateplanstatus;
    }

    /**
     * Sets the value of the rateplanstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplanstatus }
     *     
     */
    public void setRateplanstatus(Rateplanstatus value) {
        this.rateplanstatus = value;
    }

    /**
     * Gets the value of the rateplanexpirationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateplanexpirationdate() {
        return rateplanexpirationdate;
    }

    /**
     * Sets the value of the rateplanexpirationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateplanexpirationdate(String value) {
        this.rateplanexpirationdate = value;
    }

    /**
     * Gets the value of the rateplanserviceinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateplanserviceinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateplanserviceinfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rateplanserviceinfo }
     * 
     * 
     */
    public List<Rateplanserviceinfo> getRateplanserviceinfo() {
        if (rateplanserviceinfo == null) {
            rateplanserviceinfo = new ArrayList<Rateplanserviceinfo>();
        }
        return this.rateplanserviceinfo;
    }

    /**
     * Gets the value of the rateplanfamily property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRateplanfamily() {
        return rateplanfamily;
    }

    /**
     * Sets the value of the rateplanfamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRateplanfamily(BigInteger value) {
        this.rateplanfamily = value;
    }

}
