//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refillhistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refillhistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rechargehistory" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rechargehistory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paymenthistory" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}paymenthistory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="promotionalhistory" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}promotionalhistory" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refillhistory", propOrder = {
    "rechargehistory",
    "paymenthistory",
    "promotionalhistory"
})
public class Refillhistory {

    protected List<Rechargehistory> rechargehistory;
    protected List<Paymenthistory> paymenthistory;
    protected List<Promotionalhistory> promotionalhistory;

    /**
     * Gets the value of the rechargehistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rechargehistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRechargehistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rechargehistory }
     * 
     * 
     */
    public List<Rechargehistory> getRechargehistory() {
        if (rechargehistory == null) {
            rechargehistory = new ArrayList<Rechargehistory>();
        }
        return this.rechargehistory;
    }

    /**
     * Gets the value of the paymenthistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymenthistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymenthistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Paymenthistory }
     * 
     * 
     */
    public List<Paymenthistory> getPaymenthistory() {
        if (paymenthistory == null) {
            paymenthistory = new ArrayList<Paymenthistory>();
        }
        return this.paymenthistory;
    }

    /**
     * Gets the value of the promotionalhistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionalhistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionalhistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Promotionalhistory }
     * 
     * 
     */
    public List<Promotionalhistory> getPromotionalhistory() {
        if (promotionalhistory == null) {
            promotionalhistory = new ArrayList<Promotionalhistory>();
        }
        return this.promotionalhistory;
    }

}
