//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for status complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="status">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="statuscode" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}statuscode"/>
 *         &lt;element name="statusreasoncode" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}statusreasoncode" minOccurs="0"/>
 *         &lt;element name="genericstring" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}genericstring" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "status", propOrder = {

})
public class Status {

    @XmlElement(required = true)
    protected BigInteger statuscode;
    protected BigInteger statusreasoncode;
    protected String genericstring;

    /**
     * Gets the value of the statuscode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatuscode() {
        return statuscode;
    }

    /**
     * Sets the value of the statuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatuscode(BigInteger value) {
        this.statuscode = value;
    }

    /**
     * Gets the value of the statusreasoncode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusreasoncode() {
        return statusreasoncode;
    }

    /**
     * Sets the value of the statusreasoncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusreasoncode(BigInteger value) {
        this.statusreasoncode = value;
    }

    /**
     * Gets the value of the genericstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericstring() {
        return genericstring;
    }

    /**
     * Sets the value of the genericstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericstring(String value) {
        this.genericstring = value;
    }

}
