//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="data" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}data"/>
 *         &lt;element name="resultdetails" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}resultdetails"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "TPSPEchoResp")
public class TPSPEchoResp {

    @XmlElement(required = true)
    protected String data;
    @XmlElement(required = true)
    protected Resultdetails resultdetails;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the resultdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetails }
     *     
     */
    public Resultdetails getResultdetails() {
        return resultdetails;
    }

    /**
     * Sets the value of the resultdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetails }
     *     
     */
    public void setResultdetails(Resultdetails value) {
        this.resultdetails = value;
    }

}
