//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="msisdn" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}msisdn"/>
 *         &lt;element name="accountbalanceflag" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}accountbalanceflag" minOccurs="0"/>
 *         &lt;element name="boltonbalanceflag" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}boltonbalanceflag" minOccurs="0"/>
 *         &lt;element name="subscriptionstatusflag" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}subscriptionstatusflag" minOccurs="0"/>
 *         &lt;element name="rateplanchangehistoryflag" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplanchangehistoryflag" minOccurs="0"/>
 *         &lt;element name="autorenewflag" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}autorenewflag" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "TPSPRetrieveAcctDetailsReq")
public class TPSPRetrieveAcctDetailsReq {

    @XmlSchemaType(name = "integer")
    protected long msisdn;
    protected BigInteger accountbalanceflag;
    protected BigInteger boltonbalanceflag;
    protected BigInteger subscriptionstatusflag;
    protected BigInteger rateplanchangehistoryflag;
    protected BigInteger autorenewflag;

    /**
     * Gets the value of the msisdn property.
     * 
     */
    public long getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     */
    public void setMsisdn(long value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the accountbalanceflag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountbalanceflag() {
        return accountbalanceflag;
    }

    /**
     * Sets the value of the accountbalanceflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountbalanceflag(BigInteger value) {
        this.accountbalanceflag = value;
    }

    /**
     * Gets the value of the boltonbalanceflag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBoltonbalanceflag() {
        return boltonbalanceflag;
    }

    /**
     * Sets the value of the boltonbalanceflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBoltonbalanceflag(BigInteger value) {
        this.boltonbalanceflag = value;
    }

    /**
     * Gets the value of the subscriptionstatusflag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionstatusflag() {
        return subscriptionstatusflag;
    }

    /**
     * Sets the value of the subscriptionstatusflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionstatusflag(BigInteger value) {
        this.subscriptionstatusflag = value;
    }

    /**
     * Gets the value of the rateplanchangehistoryflag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRateplanchangehistoryflag() {
        return rateplanchangehistoryflag;
    }

    /**
     * Sets the value of the rateplanchangehistoryflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRateplanchangehistoryflag(BigInteger value) {
        this.rateplanchangehistoryflag = value;
    }

    /**
     * Gets the value of the autorenewflag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutorenewflag() {
        return autorenewflag;
    }

    /**
     * Sets the value of the autorenewflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutorenewflag(BigInteger value) {
        this.autorenewflag = value;
    }

}
