//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="msisdn" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}msisdn"/>
 *         &lt;element name="resultdetails" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}resultdetails"/>
 *         &lt;element name="passcodeupdateresponseinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}passcodeupdateresponseinfo" minOccurs="0"/>
 *         &lt;element name="languageupdateresponseinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}languageupdateresponseinfo" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "TPSPUpdateSubInfoResp")
public class TPSPUpdateSubInfoResp {

    @XmlSchemaType(name = "integer")
    protected long msisdn;
    @XmlElement(required = true)
    protected Resultdetails resultdetails;
    protected Passcodeupdateresponseinfo passcodeupdateresponseinfo;
    protected Languageupdateresponseinfo languageupdateresponseinfo;

    /**
     * Gets the value of the msisdn property.
     * 
     */
    public long getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     */
    public void setMsisdn(long value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the resultdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetails }
     *     
     */
    public Resultdetails getResultdetails() {
        return resultdetails;
    }

    /**
     * Sets the value of the resultdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetails }
     *     
     */
    public void setResultdetails(Resultdetails value) {
        this.resultdetails = value;
    }

    /**
     * Gets the value of the passcodeupdateresponseinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Passcodeupdateresponseinfo }
     *     
     */
    public Passcodeupdateresponseinfo getPasscodeupdateresponseinfo() {
        return passcodeupdateresponseinfo;
    }

    /**
     * Sets the value of the passcodeupdateresponseinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passcodeupdateresponseinfo }
     *     
     */
    public void setPasscodeupdateresponseinfo(Passcodeupdateresponseinfo value) {
        this.passcodeupdateresponseinfo = value;
    }

    /**
     * Gets the value of the languageupdateresponseinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Languageupdateresponseinfo }
     *     
     */
    public Languageupdateresponseinfo getLanguageupdateresponseinfo() {
        return languageupdateresponseinfo;
    }

    /**
     * Sets the value of the languageupdateresponseinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languageupdateresponseinfo }
     *     
     */
    public void setLanguageupdateresponseinfo(Languageupdateresponseinfo value) {
        this.languageupdateresponseinfo = value;
    }

}
