//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msisdn" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}msisdn"/>
 *         &lt;element name="resultdetails" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}resultdetails"/>
 *         &lt;element name="featureactionresponseinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featureactionresponseinfo" maxOccurs="100"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "resultdetails",
    "featureactionresponseinfo"
})
@XmlRootElement(name = "TPSPChangeFeatureResp")
public class TPSPChangeFeatureResp {

    @XmlSchemaType(name = "integer")
    protected long msisdn;
    @XmlElement(required = true)
    protected Resultdetails resultdetails;
    @XmlElement(required = true)
    protected List<Featureactionresponseinfo> featureactionresponseinfo;

    /**
     * Gets the value of the msisdn property.
     * 
     */
    public long getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     */
    public void setMsisdn(long value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the resultdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetails }
     *     
     */
    public Resultdetails getResultdetails() {
        return resultdetails;
    }

    /**
     * Sets the value of the resultdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetails }
     *     
     */
    public void setResultdetails(Resultdetails value) {
        this.resultdetails = value;
    }

    /**
     * Gets the value of the featureactionresponseinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureactionresponseinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureactionresponseinfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Featureactionresponseinfo }
     * 
     * 
     */
    public List<Featureactionresponseinfo> getFeatureactionresponseinfo() {
        if (featureactionresponseinfo == null) {
            featureactionresponseinfo = new ArrayList<Featureactionresponseinfo>();
        }
        return this.featureactionresponseinfo;
    }

}
