//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:24:36 PM EDT 
//


package com.classes.xjc.tpspagw32xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msisdn" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}msisdn"/>
 *         &lt;element name="resultdetails" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}resultdetails"/>
 *         &lt;element name="accountinformation" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}accountinformation"/>
 *         &lt;element name="rateplaninfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplaninfo"/>
 *         &lt;element name="rateplanchangehistoryinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}rateplanchangehistoryinfo" minOccurs="0"/>
 *         &lt;element name="featureinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}featureinfo" maxOccurs="20" minOccurs="0"/>
 *         &lt;element name="autorenewinfo" type="{http://www.ericsson.com/pps/tpspagw/03.02.00}autorenewinfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "resultdetails",
    "accountinformation",
    "rateplaninfo",
    "rateplanchangehistoryinfo",
    "featureinfo",
    "autorenewinfo"
})
@XmlRootElement(name = "TPSPRetrieveAcctDetailsResp")
public class TPSPRetrieveAcctDetailsResp {

    @XmlSchemaType(name = "integer")
    protected long msisdn;
    @XmlElement(required = true)
    protected Resultdetails resultdetails;
    @XmlElement(required = true)
    protected Accountinformation accountinformation;
    @XmlElement(required = true)
    protected Rateplaninfo rateplaninfo;
    protected Rateplanchangehistoryinfo rateplanchangehistoryinfo;
    protected List<Featureinfo> featureinfo;
    protected Autorenewinfo autorenewinfo;

    /**
     * Gets the value of the msisdn property.
     * 
     */
    public long getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     */
    public void setMsisdn(long value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the resultdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetails }
     *     
     */
    public Resultdetails getResultdetails() {
        return resultdetails;
    }

    /**
     * Sets the value of the resultdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetails }
     *     
     */
    public void setResultdetails(Resultdetails value) {
        this.resultdetails = value;
    }

    /**
     * Gets the value of the accountinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Accountinformation }
     *     
     */
    public Accountinformation getAccountinformation() {
        return accountinformation;
    }

    /**
     * Sets the value of the accountinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accountinformation }
     *     
     */
    public void setAccountinformation(Accountinformation value) {
        this.accountinformation = value;
    }

    /**
     * Gets the value of the rateplaninfo property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplaninfo }
     *     
     */
    public Rateplaninfo getRateplaninfo() {
        return rateplaninfo;
    }

    /**
     * Sets the value of the rateplaninfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplaninfo }
     *     
     */
    public void setRateplaninfo(Rateplaninfo value) {
        this.rateplaninfo = value;
    }

    /**
     * Gets the value of the rateplanchangehistoryinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplanchangehistoryinfo }
     *     
     */
    public Rateplanchangehistoryinfo getRateplanchangehistoryinfo() {
        return rateplanchangehistoryinfo;
    }

    /**
     * Sets the value of the rateplanchangehistoryinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplanchangehistoryinfo }
     *     
     */
    public void setRateplanchangehistoryinfo(Rateplanchangehistoryinfo value) {
        this.rateplanchangehistoryinfo = value;
    }

    /**
     * Gets the value of the featureinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureinfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Featureinfo }
     * 
     * 
     */
    public List<Featureinfo> getFeatureinfo() {
        if (featureinfo == null) {
            featureinfo = new ArrayList<Featureinfo>();
        }
        return this.featureinfo;
    }

    /**
     * Gets the value of the autorenewinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Autorenewinfo }
     *     
     */
    public Autorenewinfo getAutorenewinfo() {
        return autorenewinfo;
    }

    /**
     * Sets the value of the autorenewinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autorenewinfo }
     *     
     */
    public void setAutorenewinfo(Autorenewinfo value) {
        this.autorenewinfo = value;
    }

}
