//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountinformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountinformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AccountNumber" type="{http://www.ericsson.com/pps/agw/04.00.00}AccountNumber"/>
 *         &lt;element name="AccountStatusCode" type="{http://www.ericsson.com/pps/agw/04.00.00}accountstatuscode"/>
 *         &lt;element name="SubscriberDetails" type="{http://www.ericsson.com/pps/agw/04.00.00}SubscriberDetails" minOccurs="0"/>
 *         &lt;element name="Passcode" type="{http://www.ericsson.com/pps/agw/04.00.00}data4"/>
 *         &lt;element name="Market" type="{http://www.ericsson.com/pps/agw/04.00.00}data10"/>
 *         &lt;element name="SubMarket" type="{http://www.ericsson.com/pps/agw/04.00.00}data10"/>
 *         &lt;element name="AccountType" type="{http://www.ericsson.com/pps/agw/04.00.00}accounttype"/>
 *         &lt;element name="CGSA" type="{http://www.ericsson.com/pps/agw/04.00.00}data10" minOccurs="0"/>
 *         &lt;element name="ActivationDate" type="{http://www.ericsson.com/pps/agw/04.00.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="AirTimeExpiration" type="{http://www.ericsson.com/pps/agw/04.00.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="ServiceCancelDate" type="{http://www.ericsson.com/pps/agw/04.00.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="SubscriptionStatus" type="{http://www.ericsson.com/pps/agw/04.00.00}subscriptionstatuscode" minOccurs="0"/>
 *         &lt;element name="IVRLanguage" type="{http://www.ericsson.com/pps/agw/04.00.00}ivrlang" minOccurs="0"/>
 *         &lt;element name="IVRUSSDStatusCode" type="{http://www.ericsson.com/pps/agw/04.00.00}ivrussdstatuscode" minOccurs="0"/>
 *         &lt;element name="BalanceAmount" type="{http://www.ericsson.com/pps/agw/04.00.00}amount" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountinformation", propOrder = {

})
public class Accountinformation {

    @XmlElement(name = "AccountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "AccountStatusCode", required = true)
    protected BigInteger accountStatusCode;
    @XmlElement(name = "SubscriberDetails")
    protected SubscriberDetails subscriberDetails;
    @XmlElement(name = "Passcode", required = true)
    protected String passcode;
    @XmlElement(name = "Market", required = true)
    protected String market;
    @XmlElement(name = "SubMarket", required = true)
    protected String subMarket;
    @XmlElement(name = "AccountType", required = true)
    protected BigInteger accountType;
    @XmlElement(name = "CGSA")
    protected String cgsa;
    @XmlElement(name = "ActivationDate")
    protected String activationDate;
    @XmlElement(name = "AirTimeExpiration")
    protected String airTimeExpiration;
    @XmlElement(name = "ServiceCancelDate")
    protected String serviceCancelDate;
    @XmlElement(name = "SubscriptionStatus")
    protected BigInteger subscriptionStatus;
    @XmlElement(name = "IVRLanguage")
    protected BigInteger ivrLanguage;
    @XmlElement(name = "IVRUSSDStatusCode")
    protected BigInteger ivrussdStatusCode;
    @XmlElement(name = "BalanceAmount")
    @XmlSchemaType(name = "integer")
    protected Long balanceAmount;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountStatusCode() {
        return accountStatusCode;
    }

    /**
     * Sets the value of the accountStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountStatusCode(BigInteger value) {
        this.accountStatusCode = value;
    }

    /**
     * Gets the value of the subscriberDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriberDetails }
     *     
     */
    public SubscriberDetails getSubscriberDetails() {
        return subscriberDetails;
    }

    /**
     * Sets the value of the subscriberDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriberDetails }
     *     
     */
    public void setSubscriberDetails(SubscriberDetails value) {
        this.subscriberDetails = value;
    }

    /**
     * Gets the value of the passcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasscode() {
        return passcode;
    }

    /**
     * Sets the value of the passcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasscode(String value) {
        this.passcode = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarket(String value) {
        this.market = value;
    }

    /**
     * Gets the value of the subMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMarket() {
        return subMarket;
    }

    /**
     * Sets the value of the subMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMarket(String value) {
        this.subMarket = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountType(BigInteger value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the cgsa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGSA() {
        return cgsa;
    }

    /**
     * Sets the value of the cgsa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGSA(String value) {
        this.cgsa = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationDate() {
        return activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationDate(String value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the airTimeExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirTimeExpiration() {
        return airTimeExpiration;
    }

    /**
     * Sets the value of the airTimeExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirTimeExpiration(String value) {
        this.airTimeExpiration = value;
    }

    /**
     * Gets the value of the serviceCancelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCancelDate() {
        return serviceCancelDate;
    }

    /**
     * Sets the value of the serviceCancelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCancelDate(String value) {
        this.serviceCancelDate = value;
    }

    /**
     * Gets the value of the subscriptionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionStatus() {
        return subscriptionStatus;
    }

    /**
     * Sets the value of the subscriptionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionStatus(BigInteger value) {
        this.subscriptionStatus = value;
    }

    /**
     * Gets the value of the ivrLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIVRLanguage() {
        return ivrLanguage;
    }

    /**
     * Sets the value of the ivrLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIVRLanguage(BigInteger value) {
        this.ivrLanguage = value;
    }

    /**
     * Gets the value of the ivrussdStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIVRUSSDStatusCode() {
        return ivrussdStatusCode;
    }

    /**
     * Sets the value of the ivrussdStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIVRUSSDStatusCode(BigInteger value) {
        this.ivrussdStatusCode = value;
    }

    /**
     * Gets the value of the balanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * Sets the value of the balanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBalanceAmount(Long value) {
        this.balanceAmount = value;
    }

}
