//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeMultiLineReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeMultiLineReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryInformation" type="{http://www.ericsson.com/pps/agw/04.00.00}primaryMultilineInformationReq" minOccurs="0"/>
 *         &lt;element name="MemberInformation" type="{http://www.ericsson.com/pps/agw/04.00.00}memberMultilineInformationReq" minOccurs="0"/>
 *         &lt;element name="CSIconversationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Multilineevent" type="{http://www.ericsson.com/pps/agw/04.00.00}multilineevent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeMultiLineReq", propOrder = {
    "primaryInformation",
    "memberInformation",
    "csIconversationId",
    "multilineevent"
})
public class ChangeMultiLineReq {

    @XmlElement(name = "PrimaryInformation")
    protected PrimaryMultilineInformationReq primaryInformation;
    @XmlElement(name = "MemberInformation")
    protected MemberMultilineInformationReq memberInformation;
    @XmlElement(name = "CSIconversationId")
    protected String csIconversationId;
    @XmlElement(name = "Multilineevent", required = true)
    @XmlSchemaType(name = "string")
    protected Multilineevent multilineevent;

    /**
     * Gets the value of the primaryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryMultilineInformationReq }
     *     
     */
    public PrimaryMultilineInformationReq getPrimaryInformation() {
        return primaryInformation;
    }

    /**
     * Sets the value of the primaryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryMultilineInformationReq }
     *     
     */
    public void setPrimaryInformation(PrimaryMultilineInformationReq value) {
        this.primaryInformation = value;
    }

    /**
     * Gets the value of the memberInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MemberMultilineInformationReq }
     *     
     */
    public MemberMultilineInformationReq getMemberInformation() {
        return memberInformation;
    }

    /**
     * Sets the value of the memberInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberMultilineInformationReq }
     *     
     */
    public void setMemberInformation(MemberMultilineInformationReq value) {
        this.memberInformation = value;
    }

    /**
     * Gets the value of the csIconversationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSIconversationId() {
        return csIconversationId;
    }

    /**
     * Sets the value of the csIconversationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSIconversationId(String value) {
        this.csIconversationId = value;
    }

    /**
     * Gets the value of the multilineevent property.
     * 
     * @return
     *     possible object is
     *     {@link Multilineevent }
     *     
     */
    public Multilineevent getMultilineevent() {
        return multilineevent;
    }

    /**
     * Sets the value of the multilineevent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multilineevent }
     *     
     */
    public void setMultilineevent(Multilineevent value) {
        this.multilineevent = value;
    }

}
