//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for member complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="member">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://www.ericsson.com/pps/agw/04.00.00}MSISDN"/>
 *         &lt;element name="ratePlanCode" type="{http://www.ericsson.com/pps/agw/04.00.00}data10"/>
 *         &lt;element name="ratePlanStatus" type="{http://www.ericsson.com/pps/agw/04.00.00}rateplanstatus"/>
 *         &lt;element name="mldiscount" type="{http://www.ericsson.com/pps/agw/04.00.00}quantity" minOccurs="0"/>
 *         &lt;element name="ratePlanAfAmount" type="{http://www.ericsson.com/pps/agw/04.00.00}quantity" minOccurs="0"/>
 *         &lt;element name="invAccptDate" type="{http://www.ericsson.com/pps/agw/04.00.00}invAccptDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "member", propOrder = {
    "msisdn",
    "ratePlanCode",
    "ratePlanStatus",
    "mldiscount",
    "ratePlanAfAmount",
    "invAccptDate"
})
public class Member {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(required = true)
    protected String ratePlanCode;
    @XmlElement(required = true)
    protected Rateplanstatus ratePlanStatus;
    protected String mldiscount;
    protected String ratePlanAfAmount;
    protected String invAccptDate;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the ratePlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatePlanCode() {
        return ratePlanCode;
    }

    /**
     * Sets the value of the ratePlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatePlanCode(String value) {
        this.ratePlanCode = value;
    }

    /**
     * Gets the value of the ratePlanStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplanstatus }
     *     
     */
    public Rateplanstatus getRatePlanStatus() {
        return ratePlanStatus;
    }

    /**
     * Sets the value of the ratePlanStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplanstatus }
     *     
     */
    public void setRatePlanStatus(Rateplanstatus value) {
        this.ratePlanStatus = value;
    }

    /**
     * Gets the value of the mldiscount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMldiscount() {
        return mldiscount;
    }

    /**
     * Sets the value of the mldiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMldiscount(String value) {
        this.mldiscount = value;
    }

    /**
     * Gets the value of the ratePlanAfAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatePlanAfAmount() {
        return ratePlanAfAmount;
    }

    /**
     * Sets the value of the ratePlanAfAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatePlanAfAmount(String value) {
        this.ratePlanAfAmount = value;
    }

    /**
     * Gets the value of the invAccptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvAccptDate() {
        return invAccptDate;
    }

    /**
     * Sets the value of the invAccptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvAccptDate(String value) {
        this.invAccptDate = value;
    }

}
