//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MLRetrieveAcctDetailsResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MLRetrieveAcctDetailsResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryInfo" type="{http://www.ericsson.com/pps/agw/04.00.00}primaryInfo"/>
 *         &lt;element name="Members" type="{http://www.ericsson.com/pps/agw/04.00.00}members" minOccurs="0"/>
 *         &lt;element name="Invites" type="{http://www.ericsson.com/pps/agw/04.00.00}invites" minOccurs="0"/>
 *         &lt;element name="ResultDetails" type="{http://www.ericsson.com/pps/agw/04.00.00}resultdetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MLRetrieveAcctDetailsResp", propOrder = {
    "primaryInfo",
    "members",
    "invites",
    "resultDetails"
})
public class MLRetrieveAcctDetailsResp {

    @XmlElement(name = "PrimaryInfo", required = true)
    protected PrimaryInfo primaryInfo;
    @XmlElement(name = "Members")
    protected Members members;
    @XmlElement(name = "Invites")
    protected Invites invites;
    @XmlElement(name = "ResultDetails", required = true)
    protected Resultdetail resultDetails;

    /**
     * Gets the value of the primaryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryInfo }
     *     
     */
    public PrimaryInfo getPrimaryInfo() {
        return primaryInfo;
    }

    /**
     * Sets the value of the primaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryInfo }
     *     
     */
    public void setPrimaryInfo(PrimaryInfo value) {
        this.primaryInfo = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link Members }
     *     
     */
    public Members getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link Members }
     *     
     */
    public void setMembers(Members value) {
        this.members = value;
    }

    /**
     * Gets the value of the invites property.
     * 
     * @return
     *     possible object is
     *     {@link Invites }
     *     
     */
    public Invites getInvites() {
        return invites;
    }

    /**
     * Sets the value of the invites property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invites }
     *     
     */
    public void setInvites(Invites value) {
        this.invites = value;
    }

    /**
     * Gets the value of the resultDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetail }
     *     
     */
    public Resultdetail getResultDetails() {
        return resultDetails;
    }

    /**
     * Sets the value of the resultDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetail }
     *     
     */
    public void setResultDetails(Resultdetail value) {
        this.resultDetails = value;
    }

}
