//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paymentresponseinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paymentresponseinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AirTimeExpiration" type="{http://www.ericsson.com/pps/agw/04.00.00}dateYMD"/>
 *         &lt;element name="AirTimeDays" type="{http://www.ericsson.com/pps/agw/04.00.00}airtimedays"/>
 *         &lt;element name="PaymentAmount" type="{http://www.ericsson.com/pps/agw/04.00.00}Integer"/>
 *         &lt;element name="PromotionalAirtimeDays" type="{http://www.ericsson.com/pps/agw/04.00.00}promotionalairtimedays" minOccurs="0"/>
 *         &lt;element name="PromotionalBalanceAmount" type="{http://www.ericsson.com/pps/agw/04.00.00}Integer" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paymentresponseinfo", propOrder = {

})
public class Paymentresponseinfo {

    @XmlElement(name = "AirTimeExpiration", required = true)
    protected String airTimeExpiration;
    @XmlElement(name = "AirTimeDays")
    @XmlSchemaType(name = "integer")
    protected int airTimeDays;
    @XmlElement(name = "PaymentAmount", required = true)
    protected BigInteger paymentAmount;
    @XmlElement(name = "PromotionalAirtimeDays")
    @XmlSchemaType(name = "integer")
    protected Integer promotionalAirtimeDays;
    @XmlElement(name = "PromotionalBalanceAmount")
    protected BigInteger promotionalBalanceAmount;

    /**
     * Gets the value of the airTimeExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirTimeExpiration() {
        return airTimeExpiration;
    }

    /**
     * Sets the value of the airTimeExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirTimeExpiration(String value) {
        this.airTimeExpiration = value;
    }

    /**
     * Gets the value of the airTimeDays property.
     * 
     */
    public int getAirTimeDays() {
        return airTimeDays;
    }

    /**
     * Sets the value of the airTimeDays property.
     * 
     */
    public void setAirTimeDays(int value) {
        this.airTimeDays = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentAmount(BigInteger value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the promotionalAirtimeDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromotionalAirtimeDays() {
        return promotionalAirtimeDays;
    }

    /**
     * Sets the value of the promotionalAirtimeDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromotionalAirtimeDays(Integer value) {
        this.promotionalAirtimeDays = value;
    }

    /**
     * Gets the value of the promotionalBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPromotionalBalanceAmount() {
        return promotionalBalanceAmount;
    }

    /**
     * Sets the value of the promotionalBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPromotionalBalanceAmount(BigInteger value) {
        this.promotionalBalanceAmount = value;
    }

}
