//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rateplanserviceinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rateplanserviceinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Quantity" type="{http://www.ericsson.com/pps/agw/04.00.00}data40"/>
 *         &lt;element name="TotalQuantity" type="{http://www.ericsson.com/pps/agw/04.00.00}data40" minOccurs="0"/>
 *         &lt;element name="Units" type="{http://www.ericsson.com/pps/agw/04.00.00}units"/>
 *         &lt;element name="UnitsDescription" type="{http://www.ericsson.com/pps/agw/04.00.00}data40" minOccurs="0"/>
 *         &lt;element name="ServiceType" type="{http://www.ericsson.com/pps/agw/04.00.00}data40" minOccurs="0"/>
 *         &lt;element name="ServiceCode" type="{http://www.ericsson.com/pps/agw/04.00.00}data40"/>
 *         &lt;element name="AssociatedServiceInformation" type="{http://www.ericsson.com/pps/agw/04.00.00}serviceinfo" maxOccurs="20" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rateplanserviceinfo", propOrder = {
    "quantity",
    "totalQuantity",
    "units",
    "unitsDescription",
    "serviceType",
    "serviceCode",
    "associatedServiceInformation"
})
public class Rateplanserviceinfo {

    @XmlElement(name = "Quantity", required = true)
    protected String quantity;
    @XmlElement(name = "TotalQuantity")
    protected String totalQuantity;
    @XmlElement(name = "Units", required = true)
    protected BigInteger units;
    @XmlElement(name = "UnitsDescription")
    protected String unitsDescription;
    @XmlElement(name = "ServiceType")
    protected String serviceType;
    @XmlElement(name = "ServiceCode", required = true)
    protected String serviceCode;
    @XmlElement(name = "AssociatedServiceInformation")
    protected List<Serviceinfo> associatedServiceInformation;

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the totalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * Sets the value of the totalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalQuantity(String value) {
        this.totalQuantity = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnits(BigInteger value) {
        this.units = value;
    }

    /**
     * Gets the value of the unitsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitsDescription() {
        return unitsDescription;
    }

    /**
     * Sets the value of the unitsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitsDescription(String value) {
        this.unitsDescription = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the associatedServiceInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associatedServiceInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociatedServiceInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Serviceinfo }
     * 
     * 
     */
    public List<Serviceinfo> getAssociatedServiceInformation() {
        if (associatedServiceInformation == null) {
            associatedServiceInformation = new ArrayList<Serviceinfo>();
        }
        return this.associatedServiceInformation;
    }

}
