//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rateplaninforai complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rateplaninforai">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RatePlanCode" type="{http://www.ericsson.com/pps/agw/04.00.00}data10"/>
 *         &lt;element name="RatePlanName" type="{http://www.ericsson.com/pps/agw/04.00.00}data80"/>
 *         &lt;element name="RatePlanStatus" type="{http://www.ericsson.com/pps/agw/04.00.00}rateplanstatus"/>
 *         &lt;element name="ExpirationDate" type="{http://www.ericsson.com/pps/agw/04.00.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="RatePlanServiceBalanceInformation" type="{http://www.ericsson.com/pps/agw/04.00.00}rateplanserviceinfo" maxOccurs="20" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rateplaninforai", propOrder = {
    "ratePlanCode",
    "ratePlanName",
    "ratePlanStatus",
    "expirationDate",
    "ratePlanServiceBalanceInformation"
})
public class Rateplaninforai {

    @XmlElement(name = "RatePlanCode", required = true)
    protected String ratePlanCode;
    @XmlElement(name = "RatePlanName", required = true)
    protected String ratePlanName;
    @XmlElement(name = "RatePlanStatus", required = true)
    protected Rateplanstatus ratePlanStatus;
    @XmlElement(name = "ExpirationDate")
    protected String expirationDate;
    @XmlElement(name = "RatePlanServiceBalanceInformation")
    protected List<Rateplanserviceinfo> ratePlanServiceBalanceInformation;

    /**
     * Gets the value of the ratePlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatePlanCode() {
        return ratePlanCode;
    }

    /**
     * Sets the value of the ratePlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatePlanCode(String value) {
        this.ratePlanCode = value;
    }

    /**
     * Gets the value of the ratePlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatePlanName() {
        return ratePlanName;
    }

    /**
     * Sets the value of the ratePlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatePlanName(String value) {
        this.ratePlanName = value;
    }

    /**
     * Gets the value of the ratePlanStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplanstatus }
     *     
     */
    public Rateplanstatus getRatePlanStatus() {
        return ratePlanStatus;
    }

    /**
     * Sets the value of the ratePlanStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplanstatus }
     *     
     */
    public void setRatePlanStatus(Rateplanstatus value) {
        this.ratePlanStatus = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the ratePlanServiceBalanceInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratePlanServiceBalanceInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatePlanServiceBalanceInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rateplanserviceinfo }
     * 
     * 
     */
    public List<Rateplanserviceinfo> getRatePlanServiceBalanceInformation() {
        if (ratePlanServiceBalanceInformation == null) {
            ratePlanServiceBalanceInformation = new ArrayList<Rateplanserviceinfo>();
        }
        return this.ratePlanServiceBalanceInformation;
    }

}
