//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refillhistory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refillhistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RechargeHistoryInfo" type="{http://www.ericsson.com/pps/agw/04.00.00}rechargehistoryinfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentHistoryInfo" type="{http://www.ericsson.com/pps/agw/04.00.00}paymenthistoryinfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PromotionalHistoryInfo" type="{http://www.ericsson.com/pps/agw/04.00.00}promotionalhistoryinfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refillhistory", propOrder = {
    "rechargeHistoryInfo",
    "paymentHistoryInfo",
    "promotionalHistoryInfo"
})
public class Refillhistory {

    @XmlElement(name = "RechargeHistoryInfo")
    protected List<Rechargehistoryinfo> rechargeHistoryInfo;
    @XmlElement(name = "PaymentHistoryInfo")
    protected List<Paymenthistoryinfo> paymentHistoryInfo;
    @XmlElement(name = "PromotionalHistoryInfo")
    protected List<Promotionalhistoryinfo> promotionalHistoryInfo;

    /**
     * Gets the value of the rechargeHistoryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rechargeHistoryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRechargeHistoryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rechargehistoryinfo }
     * 
     * 
     */
    public List<Rechargehistoryinfo> getRechargeHistoryInfo() {
        if (rechargeHistoryInfo == null) {
            rechargeHistoryInfo = new ArrayList<Rechargehistoryinfo>();
        }
        return this.rechargeHistoryInfo;
    }

    /**
     * Gets the value of the paymentHistoryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentHistoryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentHistoryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Paymenthistoryinfo }
     * 
     * 
     */
    public List<Paymenthistoryinfo> getPaymentHistoryInfo() {
        if (paymentHistoryInfo == null) {
            paymentHistoryInfo = new ArrayList<Paymenthistoryinfo>();
        }
        return this.paymentHistoryInfo;
    }

    /**
     * Gets the value of the promotionalHistoryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionalHistoryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionalHistoryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Promotionalhistoryinfo }
     * 
     * 
     */
    public List<Promotionalhistoryinfo> getPromotionalHistoryInfo() {
        if (promotionalHistoryInfo == null) {
            promotionalHistoryInfo = new ArrayList<Promotionalhistoryinfo>();
        }
        return this.promotionalHistoryInfo;
    }

}
