//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetrieveAcctDetailsReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetrieveAcctDetailsReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MSISDN" type="{http://www.ericsson.com/pps/agw/04.00.00}MSISDN"/>
 *         &lt;element name="AccountBalanceFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *         &lt;element name="BoltonBalanceFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *         &lt;element name="SubscriptionStatusFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *         &lt;element name="LoyaltyRequestFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *         &lt;element name="RatePlanChangeHistoryFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *         &lt;element name="InvitationsListFlag" type="{http://www.ericsson.com/pps/agw/04.00.00}flag" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetrieveAcctDetailsReq", propOrder = {

})
public class RetrieveAcctDetailsReq {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(name = "AccountBalanceFlag")
    protected Boolean accountBalanceFlag;
    @XmlElement(name = "BoltonBalanceFlag")
    protected Boolean boltonBalanceFlag;
    @XmlElement(name = "SubscriptionStatusFlag")
    protected Boolean subscriptionStatusFlag;
    @XmlElement(name = "LoyaltyRequestFlag")
    protected Boolean loyaltyRequestFlag;
    @XmlElement(name = "RatePlanChangeHistoryFlag")
    protected Boolean ratePlanChangeHistoryFlag;
    @XmlElement(name = "InvitationsListFlag")
    protected Boolean invitationsListFlag;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the accountBalanceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccountBalanceFlag() {
        return accountBalanceFlag;
    }

    /**
     * Sets the value of the accountBalanceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccountBalanceFlag(Boolean value) {
        this.accountBalanceFlag = value;
    }

    /**
     * Gets the value of the boltonBalanceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBoltonBalanceFlag() {
        return boltonBalanceFlag;
    }

    /**
     * Sets the value of the boltonBalanceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBoltonBalanceFlag(Boolean value) {
        this.boltonBalanceFlag = value;
    }

    /**
     * Gets the value of the subscriptionStatusFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubscriptionStatusFlag() {
        return subscriptionStatusFlag;
    }

    /**
     * Sets the value of the subscriptionStatusFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubscriptionStatusFlag(Boolean value) {
        this.subscriptionStatusFlag = value;
    }

    /**
     * Gets the value of the loyaltyRequestFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoyaltyRequestFlag() {
        return loyaltyRequestFlag;
    }

    /**
     * Sets the value of the loyaltyRequestFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoyaltyRequestFlag(Boolean value) {
        this.loyaltyRequestFlag = value;
    }

    /**
     * Gets the value of the ratePlanChangeHistoryFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRatePlanChangeHistoryFlag() {
        return ratePlanChangeHistoryFlag;
    }

    /**
     * Sets the value of the ratePlanChangeHistoryFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRatePlanChangeHistoryFlag(Boolean value) {
        this.ratePlanChangeHistoryFlag = value;
    }

    /**
     * Gets the value of the invitationsListFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInvitationsListFlag() {
        return invitationsListFlag;
    }

    /**
     * Sets the value of the invitationsListFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInvitationsListFlag(Boolean value) {
        this.invitationsListFlag = value;
    }

}
