//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 09:46:04 PM EST 
//


package com.classes.xjc.agw40xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriberDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriberDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="FirstName" type="{http://www.ericsson.com/pps/agw/04.00.00}Name" minOccurs="0"/>
 *         &lt;element name="MiddleInitial" type="{http://www.ericsson.com/pps/agw/04.00.00}Initial" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.ericsson.com/pps/agw/04.00.00}Name" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.ericsson.com/pps/agw/04.00.00}EmailAddress" minOccurs="0"/>
 *         &lt;element name="StreetAddressLine1" type="{http://www.ericsson.com/pps/agw/04.00.00}StreetAddress" minOccurs="0"/>
 *         &lt;element name="StreetAddressLine2" type="{http://www.ericsson.com/pps/agw/04.00.00}StreetAddress" minOccurs="0"/>
 *         &lt;element name="StreetAddressLine3" type="{http://www.ericsson.com/pps/agw/04.00.00}StreetAddress" minOccurs="0"/>
 *         &lt;element name="StreetAddressLine4" type="{http://www.ericsson.com/pps/agw/04.00.00}StreetAddress" minOccurs="0"/>
 *         &lt;element name="CityAddress" type="{http://www.ericsson.com/pps/agw/04.00.00}CityAddress" minOccurs="0"/>
 *         &lt;element name="StateAddress" type="{http://www.ericsson.com/pps/agw/04.00.00}StateAddress" minOccurs="0"/>
 *         &lt;element name="ZipCode" type="{http://www.ericsson.com/pps/agw/04.00.00}String" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.ericsson.com/pps/agw/04.00.00}Country" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriberDetails", propOrder = {

})
public class SubscriberDetails {

    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleInitial")
    protected String middleInitial;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "StreetAddressLine1")
    protected String streetAddressLine1;
    @XmlElement(name = "StreetAddressLine2")
    protected String streetAddressLine2;
    @XmlElement(name = "StreetAddressLine3")
    protected String streetAddressLine3;
    @XmlElement(name = "StreetAddressLine4")
    protected String streetAddressLine4;
    @XmlElement(name = "CityAddress")
    protected String cityAddress;
    @XmlElement(name = "StateAddress")
    protected String stateAddress;
    @XmlElement(name = "ZipCode")
    protected String zipCode;
    @XmlElement(name = "Country")
    protected String country;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleInitial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleInitial() {
        return middleInitial;
    }

    /**
     * Sets the value of the middleInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleInitial(String value) {
        this.middleInitial = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the streetAddressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddressLine1() {
        return streetAddressLine1;
    }

    /**
     * Sets the value of the streetAddressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddressLine1(String value) {
        this.streetAddressLine1 = value;
    }

    /**
     * Gets the value of the streetAddressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddressLine2() {
        return streetAddressLine2;
    }

    /**
     * Sets the value of the streetAddressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddressLine2(String value) {
        this.streetAddressLine2 = value;
    }

    /**
     * Gets the value of the streetAddressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddressLine3() {
        return streetAddressLine3;
    }

    /**
     * Sets the value of the streetAddressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddressLine3(String value) {
        this.streetAddressLine3 = value;
    }

    /**
     * Gets the value of the streetAddressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddressLine4() {
        return streetAddressLine4;
    }

    /**
     * Sets the value of the streetAddressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddressLine4(String value) {
        this.streetAddressLine4 = value;
    }

    /**
     * Gets the value of the cityAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityAddress() {
        return cityAddress;
    }

    /**
     * Sets the value of the cityAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityAddress(String value) {
        this.cityAddress = value;
    }

    /**
     * Gets the value of the stateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateAddress() {
        return stateAddress;
    }

    /**
     * Sets the value of the stateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateAddress(String value) {
        this.stateAddress = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
