//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moneyBalanceInfoML" type="{http://www.ericsson.com/pps/agw/04.01.00}amount" minOccurs="0"/>
 *         &lt;element name="totalAmountDueDynamic" type="{http://www.ericsson.com/pps/agw/04.01.00}amount"/>
 *         &lt;element name="totalAmountMRC" type="{http://www.ericsson.com/pps/agw/04.01.00}amount"/>
 *         &lt;element name="totalSavingsAmount" type="{http://www.ericsson.com/pps/agw/04.01.00}amount"/>
 *         &lt;element name="allowedInvitations" type="{http://www.ericsson.com/pps/agw/04.01.00}quantity"/>
 *         &lt;element name="proAmount" type="{http://www.ericsson.com/pps/agw/04.01.00}amount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountInfo", propOrder = {
    "moneyBalanceInfoML",
    "totalAmountDueDynamic",
    "totalAmountMRC",
    "totalSavingsAmount",
    "allowedInvitations",
    "proAmount"
})
public class AccountInfo {

    @XmlSchemaType(name = "integer")
    protected Long moneyBalanceInfoML;
    @XmlSchemaType(name = "integer")
    protected long totalAmountDueDynamic;
    @XmlSchemaType(name = "integer")
    protected long totalAmountMRC;
    @XmlSchemaType(name = "integer")
    protected long totalSavingsAmount;
    @XmlElement(required = true)
    protected String allowedInvitations;
    @XmlSchemaType(name = "integer")
    protected Long proAmount;

    /**
     * Gets the value of the moneyBalanceInfoML property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMoneyBalanceInfoML() {
        return moneyBalanceInfoML;
    }

    /**
     * Sets the value of the moneyBalanceInfoML property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMoneyBalanceInfoML(Long value) {
        this.moneyBalanceInfoML = value;
    }

    /**
     * Gets the value of the totalAmountDueDynamic property.
     * 
     */
    public long getTotalAmountDueDynamic() {
        return totalAmountDueDynamic;
    }

    /**
     * Sets the value of the totalAmountDueDynamic property.
     * 
     */
    public void setTotalAmountDueDynamic(long value) {
        this.totalAmountDueDynamic = value;
    }

    /**
     * Gets the value of the totalAmountMRC property.
     * 
     */
    public long getTotalAmountMRC() {
        return totalAmountMRC;
    }

    /**
     * Sets the value of the totalAmountMRC property.
     * 
     */
    public void setTotalAmountMRC(long value) {
        this.totalAmountMRC = value;
    }

    /**
     * Gets the value of the totalSavingsAmount property.
     * 
     */
    public long getTotalSavingsAmount() {
        return totalSavingsAmount;
    }

    /**
     * Sets the value of the totalSavingsAmount property.
     * 
     */
    public void setTotalSavingsAmount(long value) {
        this.totalSavingsAmount = value;
    }

    /**
     * Gets the value of the allowedInvitations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedInvitations() {
        return allowedInvitations;
    }

    /**
     * Sets the value of the allowedInvitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedInvitations(String value) {
        this.allowedInvitations = value;
    }

    /**
     * Gets the value of the proAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProAmount() {
        return proAmount;
    }

    /**
     * Sets the value of the proAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProAmount(Long value) {
        this.proAmount = value;
    }

}
