//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountinformationrai complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountinformationrai">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AccountNumber" type="{http://www.ericsson.com/pps/agw/04.01.00}AccountNumber"/>
 *         &lt;element name="AccountStatusCode" type="{http://www.ericsson.com/pps/agw/04.01.00}accountstatuscode"/>
 *         &lt;element name="AccountType" type="{http://www.ericsson.com/pps/agw/04.01.00}accounttype"/>
 *         &lt;element name="ActivationDate" type="{http://www.ericsson.com/pps/agw/04.01.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="AirTimeExpiration" type="{http://www.ericsson.com/pps/agw/04.01.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="ServiceCancelDate" type="{http://www.ericsson.com/pps/agw/04.01.00}dateYMD" minOccurs="0"/>
 *         &lt;element name="SubscriptionStatus" type="{http://www.ericsson.com/pps/agw/04.01.00}subscriptionstatuscode" minOccurs="0"/>
 *         &lt;element name="IVRLanguage" type="{http://www.ericsson.com/pps/agw/04.01.00}ivrlang" minOccurs="0"/>
 *         &lt;element name="BalanceAmount" type="{http://www.ericsson.com/pps/agw/04.01.00}amount" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountinformationrai", propOrder = {

})
public class Accountinformationrai {

    @XmlElement(name = "AccountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "AccountStatusCode", required = true)
    protected BigInteger accountStatusCode;
    @XmlElement(name = "AccountType", required = true)
    protected BigInteger accountType;
    @XmlElement(name = "ActivationDate")
    protected String activationDate;
    @XmlElement(name = "AirTimeExpiration")
    protected String airTimeExpiration;
    @XmlElement(name = "ServiceCancelDate")
    protected String serviceCancelDate;
    @XmlElement(name = "SubscriptionStatus")
    protected BigInteger subscriptionStatus;
    @XmlElement(name = "IVRLanguage")
    protected BigInteger ivrLanguage;
    @XmlElement(name = "BalanceAmount")
    @XmlSchemaType(name = "integer")
    protected Long balanceAmount;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountStatusCode() {
        return accountStatusCode;
    }

    /**
     * Sets the value of the accountStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountStatusCode(BigInteger value) {
        this.accountStatusCode = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountType(BigInteger value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationDate() {
        return activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationDate(String value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the airTimeExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirTimeExpiration() {
        return airTimeExpiration;
    }

    /**
     * Sets the value of the airTimeExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirTimeExpiration(String value) {
        this.airTimeExpiration = value;
    }

    /**
     * Gets the value of the serviceCancelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCancelDate() {
        return serviceCancelDate;
    }

    /**
     * Sets the value of the serviceCancelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCancelDate(String value) {
        this.serviceCancelDate = value;
    }

    /**
     * Gets the value of the subscriptionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionStatus() {
        return subscriptionStatus;
    }

    /**
     * Sets the value of the subscriptionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionStatus(BigInteger value) {
        this.subscriptionStatus = value;
    }

    /**
     * Gets the value of the ivrLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIVRLanguage() {
        return ivrLanguage;
    }

    /**
     * Sets the value of the ivrLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIVRLanguage(BigInteger value) {
        this.ivrLanguage = value;
    }

    /**
     * Gets the value of the balanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * Sets the value of the balanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBalanceAmount(Long value) {
        this.balanceAmount = value;
    }

}
