//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for billingMarketInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="billingMarketInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billingMarket" type="{http://www.ericsson.com/pps/agw/04.01.00}billingMarket"/>
 *         &lt;element name="billingSubMarket" type="{http://www.ericsson.com/pps/agw/04.01.00}billingSubMarket"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "billingMarketInfo", propOrder = {
    "billingMarket",
    "billingSubMarket"
})
public class BillingMarketInfo {

    @XmlElement(required = true)
    protected String billingMarket;
    @XmlElement(required = true)
    protected String billingSubMarket;

    /**
     * Gets the value of the billingMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingMarket() {
        return billingMarket;
    }

    /**
     * Sets the value of the billingMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingMarket(String value) {
        this.billingMarket = value;
    }

    /**
     * Gets the value of the billingSubMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingSubMarket() {
        return billingSubMarket;
    }

    /**
     * Sets the value of the billingSubMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingSubMarket(String value) {
        this.billingSubMarket = value;
    }

}
