//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for featurereqinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="featurereqinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="FeatureCode" type="{http://www.ericsson.com/pps/agw/04.01.00}featurecode"/>
 *         &lt;element name="FeatureChargeFlag" type="{http://www.ericsson.com/pps/agw/04.01.00}flag"/>
 *         &lt;element name="CreditLoyaltyFlag" type="{http://www.ericsson.com/pps/agw/04.01.00}flag"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "featurereqinfo", propOrder = {

})
public class Featurereqinfo {

    @XmlElement(name = "FeatureCode", required = true)
    protected String featureCode;
    @XmlElement(name = "FeatureChargeFlag")
    protected boolean featureChargeFlag;
    @XmlElement(name = "CreditLoyaltyFlag")
    protected boolean creditLoyaltyFlag;

    /**
     * Gets the value of the featureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureCode() {
        return featureCode;
    }

    /**
     * Sets the value of the featureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureCode(String value) {
        this.featureCode = value;
    }

    /**
     * Gets the value of the featureChargeFlag property.
     * 
     */
    public boolean isFeatureChargeFlag() {
        return featureChargeFlag;
    }

    /**
     * Sets the value of the featureChargeFlag property.
     * 
     */
    public void setFeatureChargeFlag(boolean value) {
        this.featureChargeFlag = value;
    }

    /**
     * Gets the value of the creditLoyaltyFlag property.
     * 
     */
    public boolean isCreditLoyaltyFlag() {
        return creditLoyaltyFlag;
    }

    /**
     * Sets the value of the creditLoyaltyFlag property.
     * 
     */
    public void setCreditLoyaltyFlag(boolean value) {
        this.creditLoyaltyFlag = value;
    }

}
