//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetRatePlansResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRatePlansResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryMSISDN" type="{http://www.ericsson.com/pps/agw/04.01.00}MSISDN" minOccurs="0"/>
 *         &lt;element name="MemberMSISDN" type="{http://www.ericsson.com/pps/agw/04.01.00}MSISDN" minOccurs="0"/>
 *         &lt;element name="BillingMarket" type="{http://www.ericsson.com/pps/agw/04.01.00}billingMarketInfo"/>
 *         &lt;element name="DeviceType" type="{http://www.ericsson.com/pps/agw/04.01.00}deviceType"/>
 *         &lt;element name="DeviceDescription" type="{http://www.ericsson.com/pps/agw/04.01.00}string90"/>
 *         &lt;element name="TechnologyType" type="{http://www.ericsson.com/pps/agw/04.01.00}technologyType"/>
 *         &lt;element name="RatePlans" type="{http://www.ericsson.com/pps/agw/04.01.00}ratePlansInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ChangeRatePlanLimitExceeded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CSIconversationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultDetails" type="{http://www.ericsson.com/pps/agw/04.01.00}resultdetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRatePlansResp", propOrder = {
    "primaryMSISDN",
    "memberMSISDN",
    "billingMarket",
    "deviceType",
    "deviceDescription",
    "technologyType",
    "ratePlans",
    "changeRatePlanLimitExceeded",
    "csIconversationId",
    "resultDetails"
})
public class GetRatePlansResp {

    @XmlElement(name = "PrimaryMSISDN")
    protected String primaryMSISDN;
    @XmlElement(name = "MemberMSISDN")
    protected String memberMSISDN;
    @XmlElement(name = "BillingMarket", required = true)
    protected BillingMarketInfo billingMarket;
    @XmlElement(name = "DeviceType", required = true)
    protected String deviceType;
    @XmlElement(name = "DeviceDescription", required = true)
    protected String deviceDescription;
    @XmlElement(name = "TechnologyType", required = true)
    protected String technologyType;
    @XmlElement(name = "RatePlans")
    protected List<RatePlansInfo> ratePlans;
    @XmlElement(name = "ChangeRatePlanLimitExceeded", defaultValue = "false")
    protected boolean changeRatePlanLimitExceeded;
    @XmlElement(name = "CSIconversationId")
    protected String csIconversationId;
    @XmlElement(name = "ResultDetails", required = true)
    protected Resultdetail resultDetails;

    /**
     * Gets the value of the primaryMSISDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryMSISDN() {
        return primaryMSISDN;
    }

    /**
     * Sets the value of the primaryMSISDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryMSISDN(String value) {
        this.primaryMSISDN = value;
    }

    /**
     * Gets the value of the memberMSISDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberMSISDN() {
        return memberMSISDN;
    }

    /**
     * Sets the value of the memberMSISDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberMSISDN(String value) {
        this.memberMSISDN = value;
    }

    /**
     * Gets the value of the billingMarket property.
     * 
     * @return
     *     possible object is
     *     {@link BillingMarketInfo }
     *     
     */
    public BillingMarketInfo getBillingMarket() {
        return billingMarket;
    }

    /**
     * Sets the value of the billingMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingMarketInfo }
     *     
     */
    public void setBillingMarket(BillingMarketInfo value) {
        this.billingMarket = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the deviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceDescription() {
        return deviceDescription;
    }

    /**
     * Sets the value of the deviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceDescription(String value) {
        this.deviceDescription = value;
    }

    /**
     * Gets the value of the technologyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnologyType() {
        return technologyType;
    }

    /**
     * Sets the value of the technologyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnologyType(String value) {
        this.technologyType = value;
    }

    /**
     * Gets the value of the ratePlans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratePlans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatePlans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RatePlansInfo }
     * 
     * 
     */
    public List<RatePlansInfo> getRatePlans() {
        if (ratePlans == null) {
            ratePlans = new ArrayList<RatePlansInfo>();
        }
        return this.ratePlans;
    }

    /**
     * Gets the value of the changeRatePlanLimitExceeded property.
     * 
     */
    public boolean isChangeRatePlanLimitExceeded() {
        return changeRatePlanLimitExceeded;
    }

    /**
     * Sets the value of the changeRatePlanLimitExceeded property.
     * 
     */
    public void setChangeRatePlanLimitExceeded(boolean value) {
        this.changeRatePlanLimitExceeded = value;
    }

    /**
     * Gets the value of the csIconversationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSIconversationId() {
        return csIconversationId;
    }

    /**
     * Sets the value of the csIconversationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSIconversationId(String value) {
        this.csIconversationId = value;
    }

    /**
     * Gets the value of the resultDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetail }
     *     
     */
    public Resultdetail getResultDetails() {
        return resultDetails;
    }

    /**
     * Sets the value of the resultDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetail }
     *     
     */
    public void setResultDetails(Resultdetail value) {
        this.resultDetails = value;
    }

}
