//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multilineInformationResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multilineInformationResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://www.ericsson.com/pps/agw/04.01.00}MSISDN" minOccurs="0"/>
 *         &lt;element name="newRatePlanCode" type="{http://www.ericsson.com/pps/agw/04.01.00}data10" minOccurs="0"/>
 *         &lt;element name="technologyType" type="{http://www.ericsson.com/pps/agw/04.01.00}technologyTypeInfo" minOccurs="0"/>
 *         &lt;element name="oldRatePlanCode" type="{http://www.ericsson.com/pps/agw/04.01.00}data10" minOccurs="0"/>
 *         &lt;element name="deviceType" type="{http://www.ericsson.com/pps/agw/04.01.00}deviceType" minOccurs="0"/>
 *         &lt;element name="ratePlanStatus" type="{http://www.ericsson.com/pps/agw/04.01.00}rateplanstatus" minOccurs="0"/>
 *         &lt;element name="removedFeatureList" type="{http://www.ericsson.com/pps/agw/04.01.00}removedFeatureList" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multilineInformationResp", propOrder = {
    "msisdn",
    "newRatePlanCode",
    "technologyType",
    "oldRatePlanCode",
    "deviceType",
    "ratePlanStatus",
    "removedFeatureList"
})
public class MultilineInformationResp {

    @XmlElement(name = "MSISDN")
    protected String msisdn;
    protected String newRatePlanCode;
    protected String technologyType;
    protected String oldRatePlanCode;
    protected String deviceType;
    protected Rateplanstatus ratePlanStatus;
    protected List<RemovedFeatureList> removedFeatureList;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the newRatePlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewRatePlanCode() {
        return newRatePlanCode;
    }

    /**
     * Sets the value of the newRatePlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewRatePlanCode(String value) {
        this.newRatePlanCode = value;
    }

    /**
     * Gets the value of the technologyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnologyType() {
        return technologyType;
    }

    /**
     * Sets the value of the technologyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnologyType(String value) {
        this.technologyType = value;
    }

    /**
     * Gets the value of the oldRatePlanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldRatePlanCode() {
        return oldRatePlanCode;
    }

    /**
     * Sets the value of the oldRatePlanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldRatePlanCode(String value) {
        this.oldRatePlanCode = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the ratePlanStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Rateplanstatus }
     *     
     */
    public Rateplanstatus getRatePlanStatus() {
        return ratePlanStatus;
    }

    /**
     * Sets the value of the ratePlanStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rateplanstatus }
     *     
     */
    public void setRatePlanStatus(Rateplanstatus value) {
        this.ratePlanStatus = value;
    }

    /**
     * Gets the value of the removedFeatureList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removedFeatureList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemovedFeatureList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemovedFeatureList }
     * 
     * 
     */
    public List<RemovedFeatureList> getRemovedFeatureList() {
        if (removedFeatureList == null) {
            removedFeatureList = new ArrayList<RemovedFeatureList>();
        }
        return this.removedFeatureList;
    }

}
