//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ericsson.com/pps/agw/04.01.00", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.classes.xjc.agw41xsd;
