//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MSISDN" type="{http://www.ericsson.com/pps/agw/04.01.00}MSISDN"/>
 *         &lt;element name="ResultCode" type="{http://www.ericsson.com/pps/agw/04.01.00}String"/>
 *         &lt;element name="PaymentResponseInfo" type="{http://www.ericsson.com/pps/agw/04.01.00}paymentresponseinfo"/>
 *         &lt;element name="LoyaltyInformation" type="{http://www.ericsson.com/pps/agw/04.01.00}loyaltyinformation" minOccurs="0"/>
 *         &lt;element name="BalanceAmount" type="{http://www.ericsson.com/pps/agw/04.01.00}amount"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentResp", propOrder = {

})
public class PaymentResp {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(name = "ResultCode", required = true)
    protected String resultCode;
    @XmlElement(name = "PaymentResponseInfo", required = true)
    protected Paymentresponseinfo paymentResponseInfo;
    @XmlElement(name = "LoyaltyInformation")
    protected Loyaltyinformation loyaltyInformation;
    @XmlElement(name = "BalanceAmount")
    @XmlSchemaType(name = "integer")
    protected long balanceAmount;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the paymentResponseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Paymentresponseinfo }
     *     
     */
    public Paymentresponseinfo getPaymentResponseInfo() {
        return paymentResponseInfo;
    }

    /**
     * Sets the value of the paymentResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paymentresponseinfo }
     *     
     */
    public void setPaymentResponseInfo(Paymentresponseinfo value) {
        this.paymentResponseInfo = value;
    }

    /**
     * Gets the value of the loyaltyInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Loyaltyinformation }
     *     
     */
    public Loyaltyinformation getLoyaltyInformation() {
        return loyaltyInformation;
    }

    /**
     * Sets the value of the loyaltyInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Loyaltyinformation }
     *     
     */
    public void setLoyaltyInformation(Loyaltyinformation value) {
        this.loyaltyInformation = value;
    }

    /**
     * Gets the value of the balanceAmount property.
     * 
     */
    public long getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * Sets the value of the balanceAmount property.
     * 
     */
    public void setBalanceAmount(long value) {
        this.balanceAmount = value;
    }

}
