//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recharge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recharge">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="VoucherActivationNumber" type="{http://www.ericsson.com/pps/agw/04.01.00}voucheractivationnumber"/>
 *         &lt;element name="RechargeValue" type="{http://www.ericsson.com/pps/agw/04.01.00}data40"/>
 *         &lt;element name="RechargeDateTime" type="{http://www.ericsson.com/pps/agw/04.01.00}datetime"/>
 *         &lt;element name="RechargeTimeZone" type="{http://www.ericsson.com/pps/agw/04.01.00}timezone"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recharge", propOrder = {

})
public class Recharge {

    @XmlElement(name = "VoucherActivationNumber", required = true)
    protected String voucherActivationNumber;
    @XmlElement(name = "RechargeValue", required = true)
    protected String rechargeValue;
    @XmlElement(name = "RechargeDateTime", required = true)
    protected String rechargeDateTime;
    @XmlElement(name = "RechargeTimeZone", required = true)
    protected String rechargeTimeZone;

    /**
     * Gets the value of the voucherActivationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherActivationNumber() {
        return voucherActivationNumber;
    }

    /**
     * Sets the value of the voucherActivationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherActivationNumber(String value) {
        this.voucherActivationNumber = value;
    }

    /**
     * Gets the value of the rechargeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechargeValue() {
        return rechargeValue;
    }

    /**
     * Sets the value of the rechargeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechargeValue(String value) {
        this.rechargeValue = value;
    }

    /**
     * Gets the value of the rechargeDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechargeDateTime() {
        return rechargeDateTime;
    }

    /**
     * Sets the value of the rechargeDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechargeDateTime(String value) {
        this.rechargeDateTime = value;
    }

    /**
     * Gets the value of the rechargeTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechargeTimeZone() {
        return rechargeTimeZone;
    }

    /**
     * Sets the value of the rechargeTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechargeTimeZone(String value) {
        this.rechargeTimeZone = value;
    }

}
