//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rechargeresultinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rechargeresultinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MoneyBalanceChangeInformation" type="{http://www.ericsson.com/pps/agw/04.01.00}moneybalancechangeinfo"/>
 *         &lt;element name="MoneyBalanceInformation" type="{http://www.ericsson.com/pps/agw/04.01.00}moneybalanceinfo"/>
 *         &lt;element name="AirtimeExpiration" type="{http://www.ericsson.com/pps/agw/04.01.00}dateYMD"/>
 *         &lt;element name="AirTimeDays" type="{http://www.ericsson.com/pps/agw/04.01.00}airtimedays"/>
 *         &lt;element name="PromotionalAirtimeDays" type="{http://www.ericsson.com/pps/agw/04.01.00}promotionalairtimedays" minOccurs="0"/>
 *         &lt;element name="PromotionalValue" type="{http://www.ericsson.com/pps/agw/04.01.00}promotionalvalue" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rechargeresultinfo", propOrder = {

})
public class Rechargeresultinfo {

    @XmlElement(name = "MoneyBalanceChangeInformation", required = true)
    protected Moneybalancechangeinfo moneyBalanceChangeInformation;
    @XmlElement(name = "MoneyBalanceInformation", required = true)
    protected Moneybalanceinfo moneyBalanceInformation;
    @XmlElement(name = "AirtimeExpiration", required = true)
    protected String airtimeExpiration;
    @XmlElement(name = "AirTimeDays")
    @XmlSchemaType(name = "integer")
    protected int airTimeDays;
    @XmlElement(name = "PromotionalAirtimeDays")
    @XmlSchemaType(name = "integer")
    protected Integer promotionalAirtimeDays;
    @XmlElement(name = "PromotionalValue")
    protected Promotionalvalue promotionalValue;

    /**
     * Gets the value of the moneyBalanceChangeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Moneybalancechangeinfo }
     *     
     */
    public Moneybalancechangeinfo getMoneyBalanceChangeInformation() {
        return moneyBalanceChangeInformation;
    }

    /**
     * Sets the value of the moneyBalanceChangeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moneybalancechangeinfo }
     *     
     */
    public void setMoneyBalanceChangeInformation(Moneybalancechangeinfo value) {
        this.moneyBalanceChangeInformation = value;
    }

    /**
     * Gets the value of the moneyBalanceInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Moneybalanceinfo }
     *     
     */
    public Moneybalanceinfo getMoneyBalanceInformation() {
        return moneyBalanceInformation;
    }

    /**
     * Sets the value of the moneyBalanceInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moneybalanceinfo }
     *     
     */
    public void setMoneyBalanceInformation(Moneybalanceinfo value) {
        this.moneyBalanceInformation = value;
    }

    /**
     * Gets the value of the airtimeExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirtimeExpiration() {
        return airtimeExpiration;
    }

    /**
     * Sets the value of the airtimeExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirtimeExpiration(String value) {
        this.airtimeExpiration = value;
    }

    /**
     * Gets the value of the airTimeDays property.
     * 
     */
    public int getAirTimeDays() {
        return airTimeDays;
    }

    /**
     * Sets the value of the airTimeDays property.
     * 
     */
    public void setAirTimeDays(int value) {
        this.airTimeDays = value;
    }

    /**
     * Gets the value of the promotionalAirtimeDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPromotionalAirtimeDays() {
        return promotionalAirtimeDays;
    }

    /**
     * Sets the value of the promotionalAirtimeDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPromotionalAirtimeDays(Integer value) {
        this.promotionalAirtimeDays = value;
    }

    /**
     * Gets the value of the promotionalValue property.
     * 
     * @return
     *     possible object is
     *     {@link Promotionalvalue }
     *     
     */
    public Promotionalvalue getPromotionalValue() {
        return promotionalValue;
    }

    /**
     * Sets the value of the promotionalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Promotionalvalue }
     *     
     */
    public void setPromotionalValue(Promotionalvalue value) {
        this.promotionalValue = value;
    }

}
