//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.25 at 05:15:19 PM EST 
//


package com.classes.xjc.agw41xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateSubscriberInfoResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateSubscriberInfoResp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MSISDN" type="{http://www.ericsson.com/pps/agw/04.01.00}MSISDN"/>
 *         &lt;element name="ResultDetails" type="{http://www.ericsson.com/pps/agw/04.01.00}resultdetail"/>
 *         &lt;element name="PasscodeUpdateResponseInfo" type="{http://www.ericsson.com/pps/agw/04.01.00}passcodeupdateresponseinfo" minOccurs="0"/>
 *         &lt;element name="LanguageUpdateResponseInfo" type="{http://www.ericsson.com/pps/agw/04.01.00}languageupdateresponseinfo" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateSubscriberInfoResp", propOrder = {

})
public class UpdateSubscriberInfoResp {

    @XmlElement(name = "MSISDN", required = true)
    protected String msisdn;
    @XmlElement(name = "ResultDetails", required = true)
    protected Resultdetail resultDetails;
    @XmlElement(name = "PasscodeUpdateResponseInfo")
    protected Passcodeupdateresponseinfo passcodeUpdateResponseInfo;
    @XmlElement(name = "LanguageUpdateResponseInfo")
    protected Languageupdateresponseinfo languageUpdateResponseInfo;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the resultDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Resultdetail }
     *     
     */
    public Resultdetail getResultDetails() {
        return resultDetails;
    }

    /**
     * Sets the value of the resultDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resultdetail }
     *     
     */
    public void setResultDetails(Resultdetail value) {
        this.resultDetails = value;
    }

    /**
     * Gets the value of the passcodeUpdateResponseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Passcodeupdateresponseinfo }
     *     
     */
    public Passcodeupdateresponseinfo getPasscodeUpdateResponseInfo() {
        return passcodeUpdateResponseInfo;
    }

    /**
     * Sets the value of the passcodeUpdateResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Passcodeupdateresponseinfo }
     *     
     */
    public void setPasscodeUpdateResponseInfo(Passcodeupdateresponseinfo value) {
        this.passcodeUpdateResponseInfo = value;
    }

    /**
     * Gets the value of the languageUpdateResponseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Languageupdateresponseinfo }
     *     
     */
    public Languageupdateresponseinfo getLanguageUpdateResponseInfo() {
        return languageUpdateResponseInfo;
    }

    /**
     * Sets the value of the languageUpdateResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languageupdateresponseinfo }
     *     
     */
    public void setLanguageUpdateResponseInfo(Languageupdateresponseinfo value) {
        this.languageUpdateResponseInfo = value;
    }

}
