//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 11:03:24 PM EDT 
//


package com.classes.xjc.samplexsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for supportedLanguages.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="supportedLanguages">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}language">
 *     &lt;enumeration value="en"/>
 *     &lt;enumeration value="es"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "supportedLanguages")
@XmlEnum
public enum SupportedLanguages {

    @XmlEnumValue("en")
    EN("en"),
    @XmlEnumValue("es")
    ES("es");
    private final String value;

    SupportedLanguages(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SupportedLanguages fromValue(String v) {
        for (SupportedLanguages c: SupportedLanguages.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
